name: Release on tag

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build Release APK
        run: ./gradlew :app:assembleRelease --stacktrace

      - name: Checksums
        run: |
          cd app/build/outputs/apk/release
          sha256sum app-release.apk > app-release.apk.sha256

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-release.apk.sha256
